name: tota
description: Aplicativo de contratação de artistas

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  firebase_analytics: ^9.1.6
  flutter_modular: ^4.5.1+1
  carousel_slider: ^4.1.1
  fluid_bottom_nav_bar: ^1.3.0
  flutter_zoom_drawer: ^3.0.1
  font_awesome_flutter: ^10.1.0
  flutter_triple: ^1.2.7+2
  cloud_firestore: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.3.0
  fake_cloud_firestore: ^1.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
      - family: Raleway
        fonts:
          - asset: fonts/Raleway-Regular.ttf
          - asset: fonts/Raleway-Thin.ttf
            style: normal